name: Trello to Habitica Sync
on:
  repository_dispatch:
    types: [trello-to-habitica-sync]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Task
        env:
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
        run: |
          CARD_NAME=$(jq -r '.client_payload.card_name' $GITHUB_EVENT_PATH)
          CARD_DESC=$(jq -r '.client_payload.card_desc' $GITHUB_EVENT_PATH)

          curl -X POST https://habitica.com/api/v3/tasks/user \
            -H "x-api-user: $HABITICA_USER_ID" \
            -H "x-api-key: $HABITICA_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"text\": \"$CARD_NAME\",
              \"type\": \"todo\",
              \"notes\": \"$CARD_DESC\"
            }"
